server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/integration?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.jiliwangluo.spider.api.entity
